### ISSUE TITLE
gvm fails in latest build

### ISSUE THREAD

**Issue by mp3cko** [devnw/gvm#7]
Hey, this seems like a really cool project to replace my bash script used to update go.

However after a clean install I get a syntax error as shown in the picture below:

![image](https://user-images.githubusercontent.com/56165587/146077172-b8d7350f-2a78-403e-8b3a-9f2477f9b2af.png)

**Comment by benjivesterby** [comment]
What is the output of `echo $SHELL`? Also, what OS and Arch are you on?

**Comment by mp3cko** [comment]
It's `/bin/bash`
- version: 5.0.17(1)-release (x86_64-pc-linux-gnu)  

OS : 
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by benjivesterby** [comment]
Thanks. I'll take a look. Found the `shellcheck` linter and I'm fixing the errors it's identified right now. Thanks for trying it out. I'll let you know when I push a new release.

**Comment by benjivesterby** [comment]
@Maracko can you try this build? `curl -L https://github.com/devnw/gvm/releases/download/dev/gvm > $HOME/bin/gvm && chmod +x $HOME/bin/gvm`

I've corrected a number of things in the script and this should work now.

**Comment by benjivesterby** [comment]
@Maracko I've now tested this on linux, mac and both the arm64 and amd64 architectures. This should work now. I've released a new latest tag so let me now if that works.

**Comment by mp3cko** [comment]
I haven't tested it fully yet, I am on a different PC but with same OS and shell.

I managed to install a go version using `gvm 1.17.5`, however your `gvm install --next` and generally any `gvm install` commands given in the example do not work.

I get this output 
```
gvm install next --update
install is not a valid version
Go Version Manager
    Usage: gvm <version> [<args>]

      To install a released version
      Example: gvm install 1.15.5


      To install the latest development
      Example: gvm install next


      To update an existing development version
      Example: gvm install next --update
```

**Comment by mp3cko** [comment]
Other than the updating of the script itself, the switching of go versions works nicely 👍

**Comment by benjivesterby** [comment]
Ahh yeah the help docs are incorrect. It is just `gvm <version>` good catch

**Comment by benjivesterby** [comment]
@Maracko I've released a new version this afternoon that corrects a number of issues as well as auto-detects and updates new versions of the script so you don't have to re-download all the time. 

**NOTE:** You MUST use either `latest` or `dev` versions for this update feature to work.

You'll need to execute the following commands once you've downloaded the new version.

```bash
rm -rf ~/.gvm
sudo rm -rf /usr/local/go
gvm 1.17.5
```

This will correctly delete the links that were incorrectly created by the last version. Then re-run your install `gvm <version>` and it will fix those issues and correctly re-install. I've added release notes to the `v0.1.0` version indicating the change and you can read the script if you want more detail or ask here.

**Comment by benjivesterby** [comment]
@Maracko Let me know once you've tried this. If it works I'll close out the issue.

**Comment by mp3cko** [comment]
Hey @benjivesterby didn't have much chance to check it out. It seems to be working but I'll test better over the weekend.

**Comment by mp3cko** [comment]
It seems to be working correctly 😃. Closing the issue
